# Generated by Django 2.0.5 on 2018-05-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_mustbuy_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='positon',
            field=models.IntegerField(default=1),
        ),
    ]
