# Generated by Django 2.0.5 on 2018-05-21 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_mainshow'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mainshow',
            table='afx_mainshow',
        ),
    ]
