# Generated by Django 2.0.5 on 2018-05-21 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20180521_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainshow',
            old_name='markerprice1',
            new_name='marketprice1',
        ),
        migrations.RenameField(
            model_name='mainshow',
            old_name='markerprice2',
            new_name='marketprice2',
        ),
        migrations.RenameField(
            model_name='mainshow',
            old_name='markerprice3',
            new_name='marketprice3',
        ),
    ]
