# Generated by Django 2.0.5 on 2018-05-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_foodtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('productid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('productimg', models.CharField(max_length=300)),
                ('productname', models.CharField(max_length=100)),
                ('productlongname', models.CharField(max_length=100)),
                ('isxf', models.BooleanField(default=1)),
                ('pmdesc', models.IntegerField(default=1)),
                ('specifics', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('marketprice', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('categoryid', models.IntegerField(default=0)),
                ('childcid', models.IntegerField(default=0)),
                ('childcidname', models.CharField(max_length=100)),
                ('dealerid', models.CharField(max_length=10)),
                ('storenums', models.IntegerField(default=1)),
                ('productnum', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'axf_goods',
            },
        ),
    ]
