# Generated by Django 2.0.5 on 2018-05-24 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_card_deliveryaddress'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Card',
            new_name='Cart',
        ),
        migrations.AlterModelTable(
            name='cart',
            table='axf_cart',
        ),
    ]
