# Generated by Django 2.0.5 on 2018-05-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_order_ordergoods'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payType',
            field=models.IntegerField(choices=[(0, '余额'), (1, '支付宝'), (2, '微信')], default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
